version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6371
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6371:6371"
